version: '2'
services:
    newsvc-app:
        image: newsvc
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://newsvc-postgresql:5432/newsvc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    newsvc-postgresql:
        extends:
            file: postgresql.yml
            service: newsvc-postgresql
